### ISSUE TITLE
[GCP Provider] Threaded also fails when only scoped to workers with `workers_threaded: true`

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#559] opened 2023-05-26 20:45 UTC
The below happens seems to be because of the using `workers_threaded: true` in the `KCLI` parameter file when deploying `Kubernetes K3s` on `GCP`. So likely related to #551 ... However, I thought I wanted to create an issue on this specifically. As it might not be because of the same exact thing.

```text
[INFO]  systemd: Starting k3s

gcp-test-ctlplane-0 deployed on gcp
Deploying extra ctlplanes
Deploying Vms...
Waiting for disk gcp-test-ctlplane-1-disk1 to be ready
Waiting for disk gcp-test-ctlplane-1-disk2 to be ready
gcp-test-ctlplane-1 deployed on gcp
Waiting for disk gcp-test-ctlplane-2-disk1 to be ready
Waiting for disk gcp-test-ctlplane-2-disk2 to be ready
gcp-test-ctlplane-2 deployed on gcp
Deploying workers
Deploying Vms...
./kubernetes/deploy/create-cluster.sh: line 172: 29386 Segmentation fault      ( kcli --client gcp $kcliOperation kube k3s --paramfile "$plan" "$clustername" $kcliExtraArgs )
```

---

I think the cause of the above is because of `workers_threaded: true` being set. As I deployed after with that set to `workers_threaded: false` and then did not see the err.

**Comment by karmab** [comment] 2023-06-07 06:13
closing as duplicate of https://github.com/karmab/kcli/issues/551

**Closed by karmab** 2023-06-07 06:13 UTC
