### ISSUE TITLE
Include support for google-rebobinator

### ISSUE THREAD

**Issue by iranzo** [karmab/kcli#63] opened 2017-09-13 08:41 UTC
When working with slides or documents, by default the URI sets the access to the last page visited.

google-rebobinator allows document to start back at first page

Speaking with developer over telegram, he suggested an issue is opened to track this request so kcli can now integrate with google-rebobinator

**Comment by iranzo** [comment] 2017-09-13 08:41
![image](https://user-images.githubusercontent.com/312463/30368012-28780df6-9870-11e7-94a6-2a62e0689f0d.png)

**Comment by karmab** [comment] 2017-09-13 08:43
infortunately , google-rebobinator seems like a very young project, i m not able to find it and as such cant create a dedicated plan

**Comment by juanluisvaladas** [comment] 2017-09-13 08:43
+1 This breaks my workflow

**Comment by iranzo** [comment] 2017-09-13 08:45
@mikelolasagasti  can you please provide details of the plan to @karmab so he can include the required support?

Actually the product needs to be robustified before integration in stable, but a working beta would be good for workflow testing

**Comment by e-minguez** [comment] 2017-09-13 09:04
+1

**Comment by e-minguez** [comment] 2017-10-03 08:13
😞

**Comment by iranzo** [comment] 2017-10-03 08:14
I see this has been closed without a relevant commit to include the fix !

**Comment by karmab** [comment] 2017-10-03 08:40
WONT FIX NOT A BUG

**Closed by karmab** 2017-10-03 08:40 UTC
