### ISSUE TITLE
libvirt.libvirtError: Requested operation is not valid: couldn't locate a matching DNS HOST record in network network-reserve-example --  reserveip: true &  reservedns: true

### ISSUE THREAD

**Issue by rbo** [karmab/kcli#140] opened 2019-05-16 05:58 UTC
Hi,

for my ocp4 upi sandbox I need a couple of VM's without any external configuration (no kcli managed ignition) but I need DHCP with fixed IP address and DNS entries, I tried following to achieve my target ( `reserveip: true` &  `reservedns: true` ):

My plan `reserve-example.yml`:
```yaml
network-reserve-example:
 type: network
 cidr: 192.168.127.0/24

reserve-example:
 cloudinit: false
 template: rhcos-410.8.20190509.qcow2
 reserveip: true
 reservedns: true
 memory: 1024
 disks:
 - 5
 nets:
 - name: network-reserve-example
   noconf: true
   dns: 192.168.127.1
   mask: 255.255.255.0
   gateway: 192.168.127.1
   ip: 192.168.127.99
```

**and I got the error:**
```
kcli plan -f reserve-example.yml
Using drunk_einstein as name of the plan
Deploying Networks...
Network network-reserve-example deployed
Deploying Vms...
Removing old dns entry for ip 192.168.127.99
Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli', 'console_scripts', 'kcli')()
  File "/src/kcli/kvirt/cli.py", line 1399, in cli
    args.func(args)
  File "/src/kcli/kvirt/cli.py", line 789, in plan
    revert=revert, update=update, restart=restart)
  File "/src/kcli/kvirt/config.py", line 1289, in plan
    plan=plan, basedir=currentplandir, client=vmclient, onfly=onfly)
  File "/src/kcli/kvirt/config.py", line 549, in create_vm
    placement=placement)
  File "/src/kcli/kvirt/kvm/__init__.py", line 744, in create
    self.reserve_dns(name, nets=nets, domain=domain, alias=alias, force=True)
  File "/src/kcli/kvirt/kvm/__init__.py", line 1664, in reserve_dns
    network.update(2, 10, 0, oldentry, 1)
  File "/usr/lib/python3.6/site-packages/libvirt.py", line 3009, in update
    if ret == -1: raise libvirtError ('virNetworkUpdate() failed', net=self)
libvirt.libvirtError: Requested operation is not valid: couldn't locate a matching DNS HOST record in network network-reserve-example
```
**KCLI Version**
```shell
$ kcli --version
14.7

$ alias kcli
alias kcli='podman run -it --rm --security-opt label=disable -v ~/.kcli:/root/.kcli -v /var/lib/libvirt/images:/var/lib/libvirt/images -v /var/run/libvirt:/var/run/libvirt -v $PWD:/workdir karmab/kcli'
```

Am I doing something wrong? Is there a better way to have DNS and DHCP with Static IP's ?

Thanks
Robert

**Comment by karmab** [comment] 2019-05-16 15:58
hello, the following plan will do the trick
```

network-reserve-example:
 type: network
 cidr: 192.168.127.0/24

reserve-example:
 cloudinit: false
 template: rhcos-410.8.20190509.qcow2
 reservedns: true
 memory: 1024
 disks:
 - 5
 nets:
 - name: network-reserve-example
   dns: 192.168.127.1
   mask: 255.255.255.0
   gateway: 192.168.127.1
   ip: 192.168.127.99
```
basically removing reserveip since you achieve the same forcing the ip configuration, and removing noconf, because this parameter is meant to indicate no conf at all should be created for the given interface (default beeing to create cloudinit dhcp files for all nics)

not closing yet because there is probably a bug when mixing all those parameters together so i ll fix it

last but not least, note i m working on a flow to deploy ocp4 between upi and ipi ( suitable for envs where ipi has not landed yet, but there is good enough ignition support so that kcli does the missing part)

**Comment by rbo** [comment] 2019-05-16 16:19
mh, ok thanks. Unfortunately, it doesn't create the right network config, 
```xml
$ virsh net-dumpxml network-reserve-example
<network>
  <name>network-reserve-example</name>
  <uuid>0421e337-001f-4ec2-8192-3595d27b9b73</uuid>
  <metadata>
    <kvirt:info xmlns:kvirt="kvirt">
      <kvirt:plan>condescending_albattani</kvirt:plan>
    </kvirt:info>
  </metadata>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr3' stp='on' delay='0'/>
  <mac address='52:54:00:a7:ae:9a'/>
  <domain name='network-reserve-example'/>
  <dns>
    <host ip='192.168.127.99'>
      <hostname>reserve-example</hostname>
    </host>
  </dns>
  <ip address='192.168.127.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.127.2' end='192.168.127.254'/>
    </dhcp>
  </ip>
</network>
```  

What I missed:
```
<dhcp>
      <range start='10.84.3.2' end='10.84.3.254'/>
      <host mac='52:54:00:05:88:2e' name='worker-2.ocp4-upi.bohne.io' ip='10.84.3.42'/>
...
```

Basically I would like to have 
```xml
 <dns>
    <host ip='10.84.3.42'>
      <hostname>worker-2.ocp4-upi.bohne.io</hostname>
    </host>
[..snipped..]
  </dns>
    <ip address='10.84.3.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='10.84.3.2' end='10.84.3.254'/>
      <host mac='52:54:00:05:88:2e' name='worker-2.ocp4-upi.bohne.io' ip='10.84.3.42'/>
[..snipped..]
    </dhcp>
  </ip>
```

I created by hand and it works, sadly I ran into other coreos / ocp4 problems...

**Comment by karmab** [comment] 2019-05-16 17:42
this should be fixed by https://github.com/karmab/kcli/commit/13ef50bcd4cc84dc354f53164783b15e715a0902 which puts the correct information in the network xml, but i still dont see the correct ip in the vm, so i'm a bit skeptical and this host section of the network xml. 
i believe i need an additional fix so that cloudinit networking is properly applied when using reserveip

**Comment by karmab** [comment] 2019-05-16 19:10
yes, i can confirm the fix works as expected. static information is not injected when using reserveip, which makes sense.
i still see some weirdnesses when reusing older ips, though they are out of the net xml, but i'll investigate this further on its own.
releasing 14.8 to include this, give it 15mn if using rpms

**Closed by karmab** 2019-05-16 19:10 UTC
